name: Deployment
on:
    push: 
        branches: [ master ]
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Upload .env file and script via FTP
              env:
                DB_HOST: ${{ secrets.DB_HOST }}
                DB_USERNAME: ${{ secrets.DB_USERNAME }}
                DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
                DB_NAME: ${{ secrets.DB_NAME }}

              run: |

                # Generate .env file locally
                echo "DB_HOST=${DB_HOST}" > .env
                echo "DB_USERNAME=${DB_USERNAME}" >> .env
                echo "DB_PASSWORD=${DB_PASSWORD}" >> .env
                echo "DB_NAME=${DB_NAME}" >> .env

                ftp -u ftp://ftp.yoroxid.com <<EOF
                user ${{ secrets.FTP_USER }} ${{ secrets.FTP_PASSWORD }}
                cd ./www.yoroxid.com/nautilus/
                put .env
                bye
                EOF

            - name: FTP Deployer
              uses: sand4rt/ftp-deployer@v1.8
              with:
                sftp: false
                host: ${{ secrets.FTP_SERVER }}
                port: 21
                username: ${{ secrets.FTP_USER }}
                password: ${{ secrets.FTP_PASSWORD }}
                remote_folder: "./www.yoroxid.com/nautilus/"
                local_folder: "./"
                cleanup: false
                passive: true

            # - name: Setup PHP environment
            #   uses: shivammathur/setup-php@v2
            #   with:
            #     php-version: '8.1'
            #     extensions: mysqli